language: python
sudo: required
dist: xenial
python: "3.7"
cache: pip
before_install:
- pip install -r requirements.txt
script: pre-commit run --all-files
notifications:
    webhooks: https://www.travisbuddy.com/
    on_success: never
